### ISSUE TITLE
Feature request: multimeter

### ISSUE THREAD

**Issue by drodarie** [dbbs-lab/bsb-nest#4]
As a user, I need to record neurons' membrane potential during Nest simulation with bsb. This corresponds to the multimeter tool in Nest.

**Comment by Helveg** [comment]
The default `bsb-nest` device is the `external` device which defers directly to NEST:

```yaml
my_multi:
  nest_model: multimeter
  constants:
    whatever: params
    nest: needs
```
